### ISSUE TITLE
Displaying vDC informations fails.

### ISSUE THREAD

**Issue by tarak** [astratto/vcloud-rest#46]
The following fails:

```
knife vc vdc show -VV <NAME>
INFO: Using configuration from /Users/tblah/.chef//knife.rb
Description:
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/nokogiri-1.6.6.2/lib/nokogiri/xml/node_set.rb:164:in `attr': undefined method `attribute' for nil:NilClass (NoMethodError)
	from /Users/tblah/.chefdk/gem/ruby/2.1.0/gems/vcloud-rest-1.3.0/lib/vcloud-rest/vcloud/vapp.rb:38:in `block in get_vapp'
	from /Users/tblah/.chefdk/gem/ruby/2.1.0/gems/vcloud-rest-1.3.0/lib/vcloud-rest/vcloud/vapp.rb:36:in `collect'
	from /Users/tblah/.chefdk/gem/ruby/2.1.0/gems/vcloud-rest-1.3.0/lib/vcloud-rest/vcloud/vapp.rb:36:in `get_vapp'
	from /Users/tblah/.chefdk/gem/ruby/2.1.0/gems/knife-vcloud-1.3.1/lib/chef/knife/vdc/vc_vdc_show.rb:48:in `block in run'
	from /Users/tblah/.chefdk/gem/ruby/2.1.0/gems/knife-vcloud-1.3.1/lib/chef/knife/vdc/vc_vdc_show.rb:47:in `each'
	from /Users/tblah/.chefdk/gem/ruby/2.1.0/gems/knife-vcloud-1.3.1/lib/chef/knife/vdc/vc_vdc_show.rb:47:in `run'
	from /opt/chefdk/embedded/apps/chef/lib/chef/knife.rb:417:in `block in run_with_pretty_exceptions'
	from /opt/chefdk/embedded/apps/chef/lib/chef/local_mode.rb:38:in `with_server_connectivity'
	from /opt/chefdk/embedded/apps/chef/lib/chef/knife.rb:416:in `run_with_pretty_exceptions'
	from /opt/chefdk/embedded/apps/chef/lib/chef/knife.rb:213:in `run'
	from /opt/chefdk/embedded/apps/chef/lib/chef/application/knife.rb:139:in `run'
	from /opt/chefdk/embedded/apps/chef/bin/knife:25:in `<top (required)>'
	from /opt/chefdk/bin/knife:40:in `load'
	from /opt/chefdk/bin/knife:40:in `<main>'
```

If I can be of any assistance to debug let me know...

**Comment by astratto** [comment]
hey @tarak, I guess I know what the problem is...
I think it'll be fixed in the next few days. Thanks for reporting it!

**Comment by astratto** [comment]
@tarak sorry I couldn't work on this earlier...
Can I ask you to try using vcloud-rest at commit 3e49aa5fa and check if it works with that version?

Thanks
